error:
/MTools/src/api_lvl.js:1
(function (exports, require, module, __filename, __dirname) { export function getApi(num) {
                                                              ^^^^^^

SyntaxError: Unexpected token export